Repository MapServer/MapServer-documentation, pull requests merged in 2024-12, with the labels that each got.

#986 update for 8.4.0-beta2 release
  en/MIGRATION_GUIDE.txt
  en/announcements/announcements_archive.txt
  en/development/announce/8-4.txt
  en/development/announce/index.txt
  en/development/changelog/changelog-8-4.txt
  en/development/changelog/index.txt
  en/download.txt
  en/download_archives.txt
  en/errors.txt
  en/faq.txt
  en/images/label-wrap-with-maxlength.png
  en/images/label-wrap-with-pipe.png
  en/include/announcements.inc
  en/mapfile/config.txt
  en/mapfile/label.txt
  en/mapfile/map.txt
  en/mapfile/projection.txt
  en/mapscript/mapfile.txt
  en/ogc/wms_server.txt
  en/optimization/environment_variables.txt
  en/optimization/fastcgi.txt
  en/utilities/msencrypt.txt
  requirements.txt
Labels: Work in progress, backport branch-8-2

#987 update for 8.4.0-beta2 release
  en/optimization/environment_variables.txt
Labels: backport branch-8-2

#985 Document MS_WMS_ERROR_STATUS_CODE
  en/mapfile/config.txt
  en/ogc/wms_server.txt
Labels: backport branch-8-4
